app:
  name: 'shorturl'
  version: '0.6.0'

http:
#  port: '8080'
#  port: ''
#  base_url: 'http://localhost:8080'
#  base_url: ''
#  server_address: 'http://localhost'
#  server_address: ''


logger:
  log_level: 'debug'
  rollbar_env: 'shorturl'